[package]
name = "rtm_core"
version = "0.1.0"
edition.workspace = true
authors.workspace = true
rust-version.workspace = true

[lib]
crate-type = ["lib"]

[dependencies]
csv = { workspace = true }
rust_decimal = { workspace = true }

[dev-dependencies]
rstest = { workspace = true }
